[phases.setup]
nixPkgs = ["nodejs_18"]

[phases.install]
cmds = ["npm install --omit=dev --legacy-peer-deps"]

[phases.build]
cmds = ["npm run build"]

[phases.postinstall]
cmds = ["npm run db:generate"]

[start]
cmd = "npm start"
